# Generated by Django 5.1.3 on 2024-12-30 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='trabajadores/photos/')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('join_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rating', models.IntegerField()),
                ('observation', models.TextField()),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajadores.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20)),
                ('corrective_action', models.TextField()),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajadores.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('upload_date', models.DateField()),
                ('file_url', models.FileField(upload_to='trabajadores/documentos/')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajadores.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress')], max_length=20)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajadores.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.TimeField()),
                ('check_out', models.TimeField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'late'), ('absent', 'Absent')], default='present', max_length=20)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajadores.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='VacacionPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('type', models.CharField(choices=[('vacation', 'Vacation'), ('permission', 'Permission')], default='vacation', max_length=50)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'rejected'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajadores.trabajador')),
            ],
        ),
    ]
