# Generated by Django 5.1.2 on 2025-01-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0004_remove_documento_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='rut',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
