# Generated by Django 5.1.3 on 2025-01-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinofinal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='certificadosDF/'),
        ),
    ]
