# Generated by Django 5.1.3 on 2025-01-02 16:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinofinal', '0002_certificado_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='periodo',
        ),
        migrations.AddField(
            model_name='certificado',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
