# Generated by Django 5.1.2 on 2025-01-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinofinal', '0004_plasticodetalle_cantidad_kg_alter_certificado_folio'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='esBasura',
            field=models.BooleanField(default=False),
        ),
    ]
