# Generated by Django 5.1.3 on 2025-01-02 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0005_conductor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combustible',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('patente', models.CharField(max_length=50)),
                ('litros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_litro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('tarjeta', models.CharField(blank=True, max_length=50, null=True)),
                ('guia', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.conductor')),
            ],
        ),
    ]
