# Generated by Django 5.1.2 on 2025-01-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combustible',
            name='conductor',
            field=models.CharField(max_length=50),
        ),
    ]
