# Generated by Django 5.1.2 on 2025-01-14 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0002_alter_combustible_conductor'),
        ('trabajadores', '0005_alter_trabajador_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combustible',
            name='conductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajadores.trabajador'),
        ),
    ]
