# Generated by Django 5.1.3 on 2024-12-31 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('tipo_camion', models.CharField(max_length=50)),
                ('conductor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='pesajes.conductor')),
            ],
        ),
        migrations.CreateModel(
            name='CertificadoPesaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(max_length=50)),
                ('cliente', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora_ingreso', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('peso_1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pdf_ticket', models.FileField(blank=True, null=True, upload_to='certificados_pesaje/')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='pesajes.vehiculo')),
            ],
        ),
    ]
