# Generated by Django 5.1.3 on 2024-12-31 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_clients_created_at_and_more'),
        ('pesajes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(max_length=50)),
                ('vehiculo_id', models.IntegerField()),
                ('fecha', models.DateField()),
                ('hora_ingreso', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('peso_1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso_2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdf_ticket', models.FileField(blank=True, null=True, upload_to='tickets/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='clients.clients')),
            ],
        ),
        migrations.DeleteModel(
            name='CertificadoPesaje',
        ),
    ]
