# Generated by Django 5.1.3 on 2025-01-01 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_conductor'),
        ('pesajes', '0002_certificado_delete_certificadopesaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='conductor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='clients.conductor'),
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='vehiculo_id',
        ),
        migrations.AddField(
            model_name='certificado',
            name='dispatch_guide',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='transaction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='transaction_other',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados', to='pesajes.vehiculo'),
        ),
        migrations.DeleteModel(
            name='Conductor',
        ),
    ]
