# Generated by Django 5.1.3 on 2025-01-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesajes', '0003_alter_vehiculo_conductor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='vehiculo',
        ),
        migrations.AddField(
            model_name='certificado',
            name='patente',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
