# Generated by Django 5.1.3 on 2025-01-01 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_conductor'),
        ('pesajes', '0004_remove_certificado_vehiculo_certificado_patente_and_more'),
    ]
#     migrations.RemoveField(
#     model_name='certificado',
#     name='vehiculo',
# )

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='conductor',
            field=models.ForeignKey(
                default=1,  # Reemplaza "1" con un ID válido de un registro existente en la tabla "clients_conductor".
                on_delete=django.db.models.deletion.CASCADE,
                related_name='certificados',
                to='clients.conductor',
            ),
            preserve_default=False,
        ),

    ]
