# Generated by Django 5.1.3 on 2025-01-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesajes', '0005_certificado_conductor'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='tipo_camion',
            field=models.CharField(default='camion 34', max_length=50),
            preserve_default=False,
        ),
    ]
