# Generated by Django 5.1.3 on 2024-11-09 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.classification')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('transaction_type', models.CharField(choices=[('Expense', 'Expense'), ('Income', 'Income')], max_length=7)),
                ('frequency', models.CharField(choices=[('Regular', 'Regular'), ('Extraordinary', 'Extraordinary')], max_length=13)),
                ('comment', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.classification')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.subcategory')),
            ],
        ),
    ]
