# Generated by Django 5.1.3 on 2024-11-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Clients',
        ),
    ]
