# Generated by Django 5.1.3 on 2024-12-30 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clients_created_at_clients_delivery_frequency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='delivery_frequency',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='last_delivery_date',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='preferred_materials',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='total_earnings',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='updated_at',
        ),
    ]
