# Generated by Django 5.1.3 on 2025-01-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_cotizacion_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='file',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='pdf_cotizacion',
            field=models.FileField(blank=True, null=True, upload_to='cotizaciones_pdfs/'),
        ),
    ]
