# Generated by Django 5.1.2 on 2025-01-12 04:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebaritem',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Users allowed to access this sidebar item.', related_name='sidebar_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
