# Generated by Django 5.1.2 on 2025-01-12 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_sidebaritem_permission_codename'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SidebarItem',
        ),
    ]
