# Generated by Django 5.1.2 on 2025-01-12 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_sidebaritem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_access_dashboard', 'Can access dashboard'), ('can_access_combustible', 'Can access combustible'), ('can_access_fardos', 'Can access fardos'), ('can_access_vertedero', 'Can access vertedero'), ('can_access_pesaje', 'Can access pesaje'), ('can_access_cotizacion', 'Can access cotizacion'), ('can_access_disposicionfinal', 'Can access disposicion final'), ('can_access_products', 'Can access products'), ('can_access_trabajadores', 'Can access trabajadores'), ('can_access_clientes', 'Can access clientes'), ('can_access_finanzas', 'Can access finanzas'), ('can_access_configuracion', 'Can access configuracion')]},
        ),
    ]
